version: "3.9"
services:
  gdal-api-python:
    build: .
    image: "gdalpy"
    environment:
      ARBUTUS_OBJECT_ACCESS_ID: ${ARBUTUS_OBJECT_ACCESS_ID}
      ARBUTUS_OBJECT_ACCESS_KEY: ${ARBUTUS_OBJECT_ACCESS_KEY}
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
      STAC_API_HOST: ${STAC_API_HOST}
    ports:
      - "${API_PORT}:${API_PORT}"
    command: bash -c "python /bqio/lib/stacitemapi.py"
    volumes:
      - ./bqio:/bqio:rw
      - ./data:/bqio/data:rw
networks:
  default:
    name: stac-fastapi-network
